services:
  - type: web
    name: cluster-fascination-admin
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://www.clusterfascination.com
